services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_BASIC_AUTH_USER
        value: ddj905079@gmail.com
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 9319631423@Bh
